local mod = get_mod("ThirdPerson")

local camera_offset_range = {50, 400}
local camera_offset_default = 100

return {
  name = "Third Person",
  description = mod:localize("mod_description"),
  is_togglable = true,
  is_mutator = false,
  options = {
    widgets = {
      {
        setting_id = "mode",
        type = "dropdown",
        title = "mode_text",
        ["tooltip"] = "mode_tooltip",
        ["options"] = {
          {text = "option_third_person",  value = "third_person", show_widgets = {13, 14, 15, 16, 17, 18, 19}},
          {text = "option_automatic",     value = "automatic",    show_widgets = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16}},
        },
        ["default_value"] = "third_person",
        ["sub_widgets"] = {
          -- Automatic
          {
            setting_id = "automatic_ranged",
            type = "checkbox",
            title = "automatic_ranged_text",
            ["tooltip"] = "automatic_ranged_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_ranged_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_ranged_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_ranged_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_ranged_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_ranged_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_aim",
            type = "checkbox",
            title = "automatic_aim_text",
            ["tooltip"] = "automatic_aim_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_aim_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4, 5}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4, 5}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_aim_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_aim_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_aim_zoom",
                    type = "dropdown",
                    title = "zoom_text",
                    ["tooltip"] = "zoom_tooltip",
                    ["options"] = {
                      {text = "zoom_option_default_text", value = 1},
                      {text = "zoom_option_medium_text",  value = 2},
                      {text = "zoom_option_low_text",     value = 3},
                      {text = "zoom_option_off_text",     value = 4},
                    },
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_aim_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_aim_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_reload",
            type = "checkbox",
            title = "automatic_reload_text",
            ["tooltip"] = "automatic_reload_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_reload_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_reload_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_reload_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_reload_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_reload_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_vent",
            type = "checkbox",
            title = "automatic_vent_text",
            ["tooltip"] = "automatic_vent_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_vent_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_vent_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_vent_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_vent_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_vent_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_melee",
            type = "checkbox",
            title = "automatic_melee_text",
            ["tooltip"] = "automatic_melee_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_melee_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_melee_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_melee_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_melee_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_melee_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_block",
            type = "checkbox",
            title = "automatic_block_text",
            ["tooltip"] = "automatic_block_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_block_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_block_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_block_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_block_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_block_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.5,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_push",
            type = "checkbox",
            title = "automatic_push_text",
            ["tooltip"] = "automatic_push_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_push_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_push_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_push_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_push_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_push_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_stunned",
            type = "checkbox",
            title = "automatic_stunned_text",
            ["tooltip"] = "automatic_stunned_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_stunned_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_stunned_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_stunned_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_stunned_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_stunned_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_potion",
            type = "checkbox",
            title = "automatic_potion_text",
            ["tooltip"] = "automatic_potion_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_potion_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_potion_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_potion_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_potion_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_potion_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_healthkit",
            type = "checkbox",
            title = "automatic_healthkit_text",
            ["tooltip"] = "automatic_healthkit_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_healthkit_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_healthkit_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_healthkit_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_healthkit_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_healthkit_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_grenade",
            type = "checkbox",
            title = "automatic_grenade_text",
            ["tooltip"] = "automatic_grenade_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_grenade_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_grenade_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_grenade_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_grenade_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_grenade_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            setting_id = "automatic_level_event",
            type = "checkbox",
            title = "automatic_level_event_text",
            ["tooltip"] = "automatic_level_event_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_level_event_mode",
                type = "dropdown",
                title = "camera_text",
                ["tooltip"] = "camera_tooltip",
                ["options"] = {
                  {text = "option_first_person", value = "first_person", show_widgets = {3, 4}},
                  {text = "option_third_person", value = "third_person", show_widgets = {1, 2, 3, 4}},
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    setting_id = "automatic_level_event_side",
                    type = "dropdown",
                    title = "side_text",
                    ["tooltip"] = "side_tooltip",
                    ["options"] = {
                      {text = "option_right_text",  value = "right"},
                      {text = "option_left_text",   value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    setting_id = "automatic_level_event_offset",
                    type = "numeric",
                    title = "offset_text",
                    ["unit_text"] = "percent_unit_text",
                    ["tooltip"] = "offset_tooltip",
                    ["range"] = camera_offset_range,
                    ["default_value"] = camera_offset_default,
                  },
                  {
                    setting_id = "automatic_level_event_length",
                    type = "numeric",
                    title = "length_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "length_tooltip",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    setting_id = "automatic_level_event_delay",
                    type = "numeric",
                    title = "delay_text",
                    ["unit_text"] = "second_unit_text",
                    ["tooltip"] = "delay_tooltip",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          -- Normal
          {
            setting_id = "side",
            type = "dropdown",
            title = "side_text",
            ["tooltip"] = "side_tooltip",
            ["options"] = {
              {text = "option_right_text",  value = "right"},
              {text = "option_left_text",   value = "left"}
            },
            ["default_value"] = "left",
          },
          {
            setting_id = "offset",
            type = "numeric",
            title = "offset_text",
            ["unit_text"] = "percent_unit_text",
            ["tooltip"] = "offset_tooltip",
            ["range"] = camera_offset_range,
            ["default_value"] = camera_offset_default,
          },
          {
            setting_id = "zoom",
            type = "dropdown",
            title = "zoom_text",
            ["tooltip"] = "zoom_tooltip",
            ["options"] = {
              {text = "zoom_option_default_text", value = 1},
              {text = "zoom_option_medium_text",  value = 2},
              {text = "zoom_option_low_text",     value = 3},
              {text = "zoom_option_off_text",     value = 4},
            },
            ["default_value"] = 1,
          },
          {
            setting_id = "sway",
            type = "checkbox",
            title = "sway_text",
            ["tooltip"] = "sway_tooltip",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "sway_speed",
                type = "numeric",
                title = "sway_speed_text",
                ["unit_text"] = "empty_unit_text",
                ["tooltip"] = "sway_speed_tooltip",
                ["range"] = {0.1, 1},
                ["decimals_number"] = 1,
                ["default_value"] = 0.5,
              },
              {
                setting_id = "sway_normalize",
                type = "checkbox",
                title = "sway_normalize_text",
                ["tooltip"] = "sway_normalize_tooltip",
                ["default_value"] = false,
              },
              {
                setting_id = "sway_input",
                type = "dropdown",
                title = "sway_input_text",
                ["tooltip"] = "sway_input_tooltip",
                ["options"] = {
                  {text = "sway_option_keyboard_text",  value = "keyboard"},
                  {text = "sway_option_mouse_text",     value = "mouse"},
                },
                ["default_value"] = "mouse",
              },
              {
                setting_id = "sway_avoid_character",
                type = "checkbox",
                title = "sway_avoid_character_text",
                ["tooltip"] = "sway_avoid_character_tooltip",
                ["default_value"] = false,
                ["sub_widgets"] = {
                  {
                    setting_id = "sway_avoid_vertical",
                    type = "numeric",
                    title = "sway_avoid_vertical_text",
                    ["unit_text"] = "empty_unit_text",
                    ["tooltip"] = "sway_avoid_vertical_tooltip",
                    ["range"] = {0, 1},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.75,
                  },
                  {
                    setting_id = "sway_avoid_backwards",
                    type = "numeric",
                    title = "sway_avoid_backwards_text",
                    ["unit_text"] = "empty_unit_text",
                    ["tooltip"] = "sway_avoid_backwards_tooltip",
                    ["range"] = {0, 1},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.75,
                  },
                }
              },
            },
          },
          {
            setting_id = "toggle_side",
            type = "keybind",
            keybind_trigger = "pressed",
            keybind_type = "function_call",
            title = "toggle_side_text",
            ["tooltip"] = "toggle_side_tooltip",
            ["default_value"] = {},
            function_name = "toggle_side"
          },
          {
            setting_id = "switch_offset",
            type = "keybind",
            keybind_trigger = "pressed",
            keybind_type = "function_call",
            title = "switch_offset_text",
            ["tooltip"] = "switch_offset_tooltip",
            ["default_value"] = {},
            function_name = "switch_offset"
          },
          {
            setting_id = "switch_zoom",
            type = "keybind",
            keybind_trigger = "pressed",
            keybind_type = "function_call",
            title = "switch_zoom_text",
            ["tooltip"] = "switch_zoom_tooltip",
            ["default_value"] = {},
            function_name = "switch_zoom"
          },
        },
      },
      {
        setting_id = "reload_stop_when_finished",
        type = "checkbox",
        title = "reload_stop_when_finished_text",
        ["tooltip"] = "reload_stop_when_finished_tooltip",
        ["default_value"] = true,
      },
      {
        setting_id = "reload_extend_too_short",
        type = "checkbox",
        title = "reload_extend_too_short_text",
        ["tooltip"] = "reload_extend_too_short_tooltip",
        ["default_value"] = true,
      },
      {
        setting_id = "toggle_mod",
        type = "keybind",
        keybind_trigger = "pressed",
        keybind_type = "mod_toggle",
        title = "toggle_mod_text",
        ["tooltip"] = "toggle_mod_tooltip",
        ["default_value"] = {},
      },
    }
  }
}