local mod = get_mod("ThirdPerson")

return {
  name = "Third Person",
  description = mod:localize("mod_description"),
  is_togglable = true,
  is_mutator = false,
  options = {
    widgets = {
      {
        setting_id = "mode",
        type = "dropdown",
        ["text"] = "Mode",
        ["tooltip"] = "-- THIRD PERSON --\nCamera is always in third person.\n\n" ..
          "-- AUTOMATIC --\nSetup camera settings for specific situations.",
        ["options"] = {
          {text = "Third Person", value = "third_person"}, --1
          {text = "Automatic", value = "automatic"}, --2
        },
        ["default_value"] = "third_person",
        ["sub_widgets"] = {
          -- Automatic
          {
            show_widgets = {2},
            setting_id = "automatic_ranged",
            type = "checkbox",
            ["text"] = "Ranged Weapon",
            ["tooltip"] = "Camera settings when holding a ranged weapon.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_ranged_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_ranged_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_ranged_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_ranged_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_ranged_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_aim",
            type = "checkbox",
            ["text"] = "Aiming",
            ["tooltip"] = "Camera settings for aiming with a ranged weapon.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_aim_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_aim_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_aim_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_aim_zoom",
                    type = "dropdown",
                    ["text"] = "Zoom",
                    ["tooltip"] = "Change the zoom strength.",
                    ["options"] = {
                      {text = "Default", value = 1},
                      {text = "Medium", value = 2},
                      {text = "Low", value = 3},
                      {text = "Off", value = 4},
                    },
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_aim_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_aim_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_reload",
            type = "checkbox",
            ["text"] = "Reloading",
            ["tooltip"] = "Camera settings for reloading a ranged weapon.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_reload_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_reload_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_reload_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_reload_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_reload_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_vent",
            type = "checkbox",
            ["text"] = "Venting Overcharge",
            ["tooltip"] = "Camera settings when venting overcharge.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_vent_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_vent_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_vent_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_vent_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_vent_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_melee",
            type = "checkbox",
            ["text"] = "Melee Weapon",
            ["tooltip"] = "Camera settings with a melee weapon.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_melee_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_melee_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_melee_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_melee_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_melee_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_block",
            type = "checkbox",
            ["text"] = "Blocking",
            ["tooltip"] = "Camera settings for blocking with a melee weapon.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_block_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_block_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_block_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_block_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_block_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.5,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_push",
            type = "checkbox",
            ["text"] = "Pushing",
            ["tooltip"] = "Camera settings for pushing with a melee weapon.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_push_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_push_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_push_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_push_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_push_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_stunned",
            type = "checkbox",
            ["text"] = "Stunned",
            ["tooltip"] = "Camera settings when stunned after was broken.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_stunned_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_stunned_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_stunned_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_stunned_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_stunned_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_potion",
            type = "checkbox",
            ["text"] = "Holding Potion",
            ["tooltip"] = "Camera settings when holding a potion.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_potion_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_potion_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_potion_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_potion_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_potion_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_healthkit",
            type = "checkbox",
            ["text"] = "Holding Healing Item",
            ["tooltip"] = "Camera settings when holding a healing item.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_healthkit_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_healthkit_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_healthkit_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_healthkit_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_healthkit_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_grenade",
            type = "checkbox",
            ["text"] = "Holding Grenades",
            ["tooltip"] = "Camera settings when holding a grenade.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_grenade_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_grenade_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_grenade_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_grenade_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_grenade_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          {
            show_widgets = {2},
            setting_id = "automatic_level_event",
            type = "checkbox",
            ["text"] = "Carrying Event Item",
            ["tooltip"] = "Camera settings when carrying objective items.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "automatic_level_event_mode",
                type = "dropdown",
                ["text"] = "Mode",
                ["tooltip"] = "Camera mode to be used by this event.",
                ["options"] = {
                  {text = "First Peson", value = "first_person"}, --1
                  {text = "Third Person", value = "third_person"}, --2
                },
                ["default_value"] = "first_person",
                ["sub_widgets"] = {
                  {
                    show_widgets = {2},
                    setting_id = "automatic_level_event_side",
                    type = "dropdown",
                    ["text"] = "Side",
                    ["tooltip"] = "Choose if the camera is to left or right of your character.",
                    ["options"] = {
                      {text = "Right", value = "right"},
                      {text = "Left", value = "left"},
                    },
                    ["default_value"] = "right",
                  },
                  {
                    show_widgets = {2},
                    setting_id = "automatic_level_event_offset",
                    type = "numeric",
                    ["text"] = "Offset",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the distance between the camera and the character.",
                    ["range"] = {50, 400},
                    ["default_value"] = 100,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_level_event_length",
                    type = "numeric",
                    ["text"] = "Length",
                    ["unit_text"] = "",
                    ["tooltip"] = "Change the length of the transition.",
                    ["range"] = {0.1, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 1,
                  },
                  {
                    show_widgets = {1, 2},
                    setting_id = "automatic_level_event_delay",
                    type = "numeric",
                    ["text"] = "Delay",
                    ["unit_text"] = " sec",
                    ["tooltip"] = "Change the delay of the transition.",
                    ["range"] = {0, 2},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.1,
                  },
                },
              },
            },
          },
          -- Normal
          {
            show_widgets = {1},
            setting_id = "side",
            type = "dropdown",
            ["text"] = "Side",
            ["tooltip"] = "Choose if the camera is to left or right of your character.",
            ["options"] = {
              {text = "Right", value = "right"},
              {text = "Left", value = "left"}
            },
            ["default_value"] = "left",
          },
          {
            show_widgets = {1},
            setting_id = "offset",
            type = "numeric",
            ["text"] = "Offset",
            ["unit_text"] = "",
            ["tooltip"] = "Change the distance between the camera and the character.",
            ["range"] = {50, 400},
            ["default_value"] = 100,
          },
          {
            show_widgets = {1},
            setting_id = "zoom",
            type = "dropdown",
            ["text"] = "Zoom",
            ["tooltip"] = "Change the zoom strength.",
            ["options"] = {
              {text = "Default", value = 1},
              {text = "Medium", value = 2},
              {text = "Low", value = 3},
              {text = "Off", value = 4},
            },
            ["default_value"] = 1,
          },
          {
            show_widgets = {1, 2},
            setting_id = "sway",
            type = "checkbox",
            ["text"] = "Dynamic Swaying",
            ["tooltip"] = "In third person the camera smoothly sways from left to right when strafing.",
            ["default_value"] = false,
            ["sub_widgets"] = {
              {
                setting_id = "sway_speed",
                type = "numeric",
                ["text"] = "Speed",
                ["unit_text"] = "",
                ["tooltip"] = "Camera sway speed.",
                ["range"] = {0.1, 1},
                ["decimals_number"] = 1,
                ["default_value"] = 0.5,
              },
              {
                setting_id = "sway_normalize",
                type = "checkbox",
                ["text"] = "Normalize",
                ["tooltip"] = "Smoothly resets sway amount when not strafing.",
                ["default_value"] = false,
              },
              {
                setting_id = "sway_input",
                type = "dropdown",
                ["text"] = "Input Type",
                ["tooltip"] = "The type of input used for camera sway.",
                ["options"] = {
                  {text = "Keyboard", value = "keyboard"},
                  {text = "Mouse", value = "mouse"},
                },
                ["default_value"] = "mouse",
              },
              {
                setting_id = "sway_avoid_character",
                type = "checkbox",
                ["text"] = "Avoid Character",
                ["tooltip"] = "Avoids the character being in front of the camera.",
                ["default_value"] = false,
                ["sub_widgets"] = {
                  {
                    setting_id = "sway_avoid_vertical",
                    type = "numeric",
                    ["text"] = "Vertical",
                    ["unit_text"] = "",
                    ["tooltip"] = "The strength of sway applied vertically to avoid the character.",
                    ["range"] = {0, 1},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.75,
                  },
                  {
                    setting_id = "sway_avoid_backwards",
                    type = "numeric",
                    ["text"] = "Backwards",
                    ["unit_text"] = "",
                    ["tooltip"] = "The strength of sway applied backwards to avoid the character.",
                    ["range"] = {0, 1},
                    ["decimals_number"] = 1,
                    ["default_value"] = 0.75,
                  },
                }
              },
            },
          },
          {
            show_widgets = {1},
            setting_id = "toggle_side",
            type = "keybind",
            keybind_trigger = "pressed",
            keybind_type = "function_call",
            ["text"] = "Toggle Side",
            ["tooltip"] = "Toggle side left / right.",
            ["default_value"] = {},
            function_name = "toggle_side"
          },
          {
            show_widgets = {1},
            setting_id = "switch_offset",
            type = "keybind",
            keybind_trigger = "pressed",
            keybind_type = "function_call",
            ["text"] = "Switch Offset",
            ["tooltip"] = "Switch camera offset.",
            ["default_value"] = {},
            function_name = "switch_offset"
          },
          {
            show_widgets = {1},
            setting_id = "switch_zoom",
            type = "keybind",
            keybind_trigger = "pressed",
            keybind_type = "function_call",
            ["text"] = "Switch Zoom",
            ["tooltip"] = "Switch camera zoom.",
            ["default_value"] = {},
            function_name = "switch_zoom"
          },
        },
      },
      {
        setting_id = "reload_stop_when_finished",
        type = "checkbox",
        ["text"] = "Stop Reload When Finished",
        ["tooltip"] = "Toggle stop reload when finished off or on.\n\n" ..
          "The first- and third person animations can differ a lot.\n" ..
          "Especially the reload animation for ranged weapons.\n" ..
          "Stops third person reload animation after the correct time.",
        ["default_value"] = true,
      },
      {
        setting_id = "reload_extend_too_short",
        type = "checkbox",
        ["text"] = "Extend Short Reload Animations",
        ["tooltip"] = "Toggle extend short animations off or on.\n\n" ..
          "The first- and third person animations can differ a lot.\n" ..
          "Especially the reload animation for ranged weapons.\n" ..
          "Repeats third person reload animation if too short.",
        ["default_value"] = true,
      },
      {
        setting_id = "toggle_mod",
        type = "keybind",
        keybind_trigger = "pressed",
        keybind_type = "function_call",
        ["text"] = "Toggle",
        ["tooltip"] = "Toggle third person on / off.",
        ["default_value"] = {},
        function_name = "toggle_mod_state"
      },
    }
  }
}